### ISSUE TITLE
Germany changed back to 19% tax rate

### ISSUE THREAD

**Issue by Yetispapa** [mpociot/vat-calculator#104]
Hi @mpociot,

first of all thanks for the great project! I just wanted to mentioned that from 01.01.2021 Germany changed back to 19% instead of 16% tax rate. Could you please change the rate back. For now I rollback to version 2.4.0 until the rate is fixed.

Thank you 

Cheers from munich

**Comment by felixgoldstein** [comment]
there is already an open pull request, i'm also waiting for it to be merged

**Comment by felixgoldstein** [comment]
https://github.com/mpociot/vat-calculator/pull/102

**Comment by driesvints** [comment]
Will be in the next patch release, thanks.
