### ISSUE TITLE
SoapFault

### ISSUE THREAD

**Issue by Reached** [mpociot/vat-calculator#13]
Hi,

I get this error (have not changed anything to my code, just booted up my VM this morning):

```
SoapFault in VatCalculator.php line 115:
SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl' : failed to load external entity "http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl"
```

Is it just a problem on ec.europe's part maybe?

**Comment by mpociot** [comment]
Hi,

Looks like this is an issue on the SOAP / EU service aide. Nevertheless we need to catch the SOAP error if this happens.

**Comment by Reached** [comment]
Ye it seemed like it was just a temporary issue :)

**Comment by morenDev** [comment]
What if I want handle SoapFault Exception in a different way in 'isValidVATNumber' method?

**Comment by marcnewton** [comment]
No longer exists: http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl
