### ISSUE TITLE
Norway tax rule

### ISSUE THREAD

**Issue by dadastudio** [mpociot/vat-calculator#14]
Hi,

Since, Norway is not a member of UE, it shouldn't be in $taxRules array. :)
http://ec.europa.eu/taxation_customs/vies/faqvies.do#item_11

Thanks.

**Comment by mpociot** [comment]
Hi,

Yes - while it's true that Norway is not part of the EU, the country still has its own VAT service and rules. 

So you basically have to register for the Norwegian VAT service if you sell more than 7.000€ to Norwegian customers per year. In this case you would need to register for the VAT service and collect Norwegian VAT using the provided rate. 

Take a look here, for more information: http://www.voesnorway.com/
