### ISSUE TITLE
VAT Number not UE

### ISSUE THREAD

**Issue by nacr-dev** [mpociot/vat-calculator#17]
This is a question not a issue, what will be the behavior of vat validation if we try to validate a vat number that is not UE?

Tks

**Comment by mpociot** [comment]
The validation will fail, because it uses a SOAP service provided by the EU, which can only validate european VAT IDs.

**Comment by nacr-dev** [comment]
So in that case the form validation will fail correct?

So it would be interesting to verify if the $countryCode is present in $taxRules and then respond accordingly?

**Comment by mpociot** [comment]
Yeah right. I think the best (and to my knowledge) most common solution is to only give the ability to enter a VAT ID when the selected country is in the EU.

**Comment by mpociot** [comment]
I just updated the package to provide a new method `shouldCollectVAT($countryCode)`.

You can use this method to see if you need to collect taxes for the given country code.

**Comment by nacr-dev** [comment]
Cool m:8ball: tks :+1:
