### ISSUE TITLE
Fatal error: while using version 1.6.2

### ISSUE THREAD

**Issue by nacr-dev** [mpociot/vat-calculator#19]
Hello @mpociot , I run into this error:

``` Fatal error: Call to undefined method Mpociot\VatCalculator\VatCalculator::shouldCollectVAT()```

My version is: mpociot/vat-calculator (1.6.2)

I have checked the package in vender folder and the shouldCollectVAT method in VatCalculator.php is not present.

Nuno

**Comment by mpociot** [comment]
Ha - you're right. I forgot to create a new release containing the newly added `shouldCollectVAT` method.

Please run `composer up` and you should get version 1.6.3

**Comment by nacr-dev** [comment]
Tks
