### ISSUE TITLE
Decimal separator

### ISSUE THREAD

**Issue by michellaurent** [mpociot/vat-calculator#24]
Allow the specify if the decimal separator should be a coma or a point in js script.

**Comment by mpociot** [comment]
Thanks for the feedback. It will be available with the version 2.0, which will be released soon.

https://github.com/mpociot/vat-calculator/blob/95f73e30e8356439345cce743af911e3c81daa2c/README.md#use-a-custom-formatter-function-to-modify-calculation-result-html
