### ISSUE TITLE
Calculator will always return 0 for tax rate on a country with post code exceptions

### ISSUE THREAD

**Issue by rossbearman** [mpociot/vat-calculator#30]
If you supply a country code and post code for a country that has post code exceptions listed, but the postcode doesn't match any of the exceptions, the VAT is zero rated by [this code](https://github.com/mpociot/vat-calculator/blob/master/src/Mpociot/VatCalculator/VatCalculator.php#L550). This means if you supply a postal code, the countries of AT, CH, DE, ES, GB, GR, IT and PT all get 0 tax applied.

To reproduce, visit this URL on a site with the VAT calculator installed, which should, due to the random post code, return the standard VAT rate, but instead returns 0:
`vatcalculator/calculate?netPrice=20&country=ES&postal_code=dso8576yj89f5`

Or this valid UK post code, which also gets zero rated:
`vatcalculator/calculate?netPrice=20&country=GB&postal_code=S1A%202AA`

When each iteration of the `foreach` loop doesn't match the postcode to an exception, it continues to the next, until when the loop eventually breaks it hits the `return 0;`

Presumably instead of return 0, the condition should just be inverted so that [lines 547 to 563](https://github.com/mpociot/vat-calculator/blob/master/src/Mpociot/VatCalculator/VatCalculator.php#L547-L563) are replaced with this:

```php
        if (isset($this->postalCodeExceptions[$countryCode]) && $postalCode !== null) {
            foreach ($this->postalCodeExceptions[$countryCode] as $postalCodeException) {
                if (!preg_match($postalCodeException['postalCode'], $postalCode)) {
                    continue;
                }
                if (isset($postalCodeException['name'])) {
                    return $this->taxRules[$postalCodeException['code']]['exceptions'][$postalCodeException['name']];
                }

                return $this->taxRules[$postalCodeException['code']]['rate'];
            }
        }
        
        return isset($this->taxRules[strtoupper($countryCode)]['rate']) ? $this->taxRules[strtoupper($countryCode)]['rate'] : 0;
```

**Comment by mpociot** [comment]
Would you be open to submit a pull request for this issue?
