### ISSUE TITLE
Standalone... requires Facade

### ISSUE THREAD

**Issue by IvoPereira** [mpociot/vat-calculator#50]
Hello,

I have been exploring the most starred options in what regards VAT validation and company information retrieval and I've come up with your repository.

As I've moved forward the documentation and the installation I have faced some problems regarding your Facade implementation.

I have a project where I am using Yii2 as the framework. From what I've seen the main focus of this repo is Laravel and Standalone options. I would guess that Standalone would work for me, however my framework does not seem to accept facades as Laravel does.

I would like to ask, if removing the Facade Pattern dependency would eventually come to the roadmap?

Thanks and congrats for the great work!

**Comment by mpociot** [comment]
Hello,

can you tell me where you found the facade pattern dependency? I know that this library comes with a facade than can be dropped into an existing Laravel application, but it is by no means a requirement/dependency and the whole code works just fine without Laravel at all.

**Comment by IvoPereira** [comment]
Hey again.

As the time you replied, I have just noticed I had imported the wrong dependency
``Mpociot\VatCalculator\Facades\VatCalculator`` instead of ``Mpociot\VatCalculator\VatCalculator`` and that's why it was reporting a missing dependency.

Looks like solved, I guess.

Thanks once again!

**Comment by cannect** [comment]
Hi thanks @IvoPereira for your comment on PHPStorm's autocompletion, I got fooled by the exact same issue, great you provided your answer here!

However maybe it is an idea to check why the autocompletion does not work with `mpociot/vatcalculator` where it does with other repo's for laravel.

**Comment by cannect** [comment]
I have to correct myself: I have to use `use Mpociot\VatCalculator\Facades\VatCalculator;`  to run code like this:
```
$grossPrice = VatCalculator::calculateNet( 24.00, 'DE' );
```

Otherwise I have to use `use Mpociot\VatCalculator\VatCalculator` and then:
```
$vatCalc = new VatCalculator();
$grossPrice = $vatCalc->calculateNet( 24.00, 'DE' );
```

Information:
- Plain Laravel 5.6.*
- did `composer require mpociot/vat-calculator`
- then above code
