### ISSUE TITLE
VAT validation suddenly failing with SoapFault

### ISSUE THREAD

**Issue by ivanvermeyen** [mpociot/vat-calculator#54]
Hi,

For some mysterious reason, the VAT validation on our form is suddenly failing, even with valid numbers. It seems I always end up in the `catch SoapFault` block that is returning `false`.

https://github.com/mpociot/vat-calculator/blob/2.2.0/src/Mpociot/VatCalculator/VatCalculator.php#L636

Is anyone else getting this?

I'm using v2.2.0 with Laravel 5.4.

**Comment by vool** [comment]
Yes same issue here 

v2.0.2 and Laravel 5.3

**Comment by ivanvermeyen** [comment]
I think it's because the underlying service is unavailable, as metioned in [this previous issue](https://github.com/mpociot/vat-calculator/issues/13).
I think we do need to have some fallback strategy, because blocking form submission if the service is down is not a good thing... Had to disable the check for now...

**Comment by spaze** [comment]
Just hit a similar issue and have done a bit research and I believe this was fixed in #52 released as 2.3.0 - it would throw an exception now.
