### ISSUE TITLE
Set default value for individuals outside of the EU

### ISSUE THREAD

**Issue by scottybo** [mpociot/vat-calculator#55]
We're based in the UK and are required to add VAT to all purchases from us if the buyer is an individual (businesses don't get taxed).

Is it possible set a rule for this? i.e. if the user is outside any of the countries listed and is an individual set VAT rate to XX otherwise set to XX

**Comment by ruudy-es** [comment]
You can extend class functionality or implement that specific case in top of the calculation.

Look like a really specific case and maybe is not going to be covered soon.

**Comment by scottybo** [comment]
It's a rule specific to the UK (rather than just us) so I'm not sure whether you go do things to the country level of just the EU?

**Comment by denjaland** [comment]
I don't think it's specific for the UK... Same rule applies in BE.
Individuals outside of the EU have to be charged BE tax...

**Comment by driesvints** [comment]
You can already do this by marking if the calculation is done for an individual or a company: https://github.com/mpociot/vat-calculator#calculate-the-gross-price
