### ISSUE TITLE
I believe there is a problem with Business Country Code set to UK

### ISSUE THREAD

**Issue by FlaviuRadulescu** [mpociot/vat-calculator#60]
--- update: I just figured out that I should use GB instead of UK, so there is no BUG. You can delete my bug report. ----

Hello,
I believe there is a bug in the way the vat calculator handle the VAT in UK.

 if I set the BusinessCountryCode to UK and try to calculate the tax/gross price for an individual in UK I get TAX 0 which is wrong as all the business in UK should charge the 19% to all the invoices to individuals.
$vatCalculator = new Mpociot\VatCalculator\VatCalculator();
$vatCalculator->setBusinessCountryCode('UK');
//$countryCode = $vatCalculator->getIPBasedCountry();
$grossPrice = $vatCalculator->calculate( 10, 'UK' );
$taxRate    = $vatCalculator->getTaxRate(); 
 
The result is that taxRate is 0. 

I am doing something wrong or there is a real bug?

Thank you,

Flaviu

**Comment by nasyrov** [comment]
@FlaviuRadulescu, the correct country code is GB
