### ISSUE TITLE
Add Switzerland to the VAT Calculator

### ISSUE THREAD

**Issue by Magelfik** [mpociot/vat-calculator#66]
Hey there,

first, thank you for this wonderful package. It's really helpful especially combined with Laravel Spark.

I was wondering if it you could add the Swiss VAT to your package ? Switzerland's not in the EU and has a VAT that differs from EU's percentage. It is a 7.7 % tax (source : [The Swiss authorities](https://www.ch.ch/en/vat-rates-switzerland/) ).

It would really help me finish my app (many of my users will be in Switzerland). Using the config.php does not seem to be changing much (maybe I'm using it wrong ?) :
```
    'rules' => [
        // 'XX' => 0.17,
	    'CH' => 0.077
    ],
```

Thank you in advance for your help. 

EDIT : I see this has already been discussed (https://github.com/mpociot/vat-calculator/issues/29), however I believe this package could also add Switzerland, especially since Norway has been added. Since Norway's not in the EU, I believe Switzerland should be in there too.

**Comment by driesvints** [comment]
Seems to be added in https://github.com/mpociot/vat-calculator/pull/69

**Comment by driesvints** [comment]
Actually, CH shouldn't have been added as it's not part of the EU.
