### ISSUE TITLE
For Turkey returning invalid VAT number

### ISSUE THREAD

**Issue by Bhuvana94** [mpociot/vat-calculator#67]
Thank you so much for the library, it was very helpful.

I'm facing issue with Turkey country, can you please look in to this?
I have provided valid VAT only, but it's returning Invalid VAT.

But as Turkey belongs to EU, it should validate right ?
please let me know if I'm wrong.

Thanks in advance!

**Comment by driesvints** [comment]
Seems to be solved already in https://github.com/mpociot/vat-calculator/pull/69

**Comment by driesvints** [comment]
Actually, Turkey shouldn't have been added as it's not part of the EU.
