### ISSUE TITLE
Setting own company's country?

### ISSUE THREAD

**Issue by webcraft** [mpociot/vat-calculator#8]
Hi Marcel,

First, thank you for this very useful package.

One feature that seems to be missing, is having the possibility to set your 'home' country. If I understand the EU VAT rules correctly, VAT should be charged to companies based in your own country. So, if my company is based in Belgium and I sell to another Belgian company, I have to charge VAT. Right?

How should I handle this situation with this package? It seems VAT 0% is applied to all companies, regardless of the country.
If it's not in there yet, I can see if I can make a pull request one of the coming days if you like.

**Comment by mpociot** [comment]
Hey,

please take a look at the following picture, which explains when you need to apply which VAT rate.

![vat](https://cloud.githubusercontent.com/assets/804684/12265035/03593b8c-b93b-11e5-9b9b-32fddd541876.png)

**Comment by webcraft** [comment]
Ok, that confirms what I thought, but then I don't see how to account for the top-left scenario using this package (Same EU country, B2B).

If I would do `VatCalculator::calculate($netPrice = 100, $countryCode = 'BE', $company = true)`, then I'll get 0% VAT instead of the required 21% (being based in Belgium myself).
Granted, I could work around this by setting `$company` to `false` only if it's a Belgian company, but that feels a bit awkward and doesn't help to explain the rule through the code. Moreover, that solution doesn't hold if I'm using the Javascript frontend integration.

It would feel more natural if you could set a home country in the config or via a setter, so that the calculator can account for that. Or did I overlook something?

**Comment by mpociot** [comment]
Oh you're absolutely right.

Placing a home country in the package settings would be the best option I think.
The default could be the app locale.

I'll publish an updated version later today :+1:

**Comment by webcraft** [comment]
Super :+1: 

The app locale as default is an option, but they're not quite the same: the locale stands for language, and here we need a country. Sometimes it's the same, sometimes not. That can be dangerous if you're not paying attention: an Austrian can have `de` as locale, but doesn't want to have Germany as his home country. I would prefer leaving it empty as default.

**Comment by mpociot** [comment]
Yeah, or we leave it empty which will result in the current behavior.

**Comment by webcraft** [comment]
Agreed!

**Comment by webcraft** [comment]
Awesome, thanks a lot man!

**Comment by IvalinV** [comment]
Hi, @mpociot 

First of all great package thank you for it.

I have a problem setting the business country code.

What I did so far:

1. Publish the config files: `php artisan vendor:publish --provider="Mpociot\VatCalculator\VatCalculatorServiceProvider"`
2. Set country code in `/config/vat_calculater.php` `'business_country_code' => 'BG',`
3. Check the tax rate for a company from the same coutry: ` $vatCalculator->calculate(114.99, 'BG', '7002', true)`
but I get the same value and the `getTaxRate()` returns 0.

Any suggestions ?
