### ISSUE TITLE
Laravel 6 compatability - Carbon v2

### ISSUE THREAD

**Issue by scottybo** [mpociot/vat-calculator#87]
Laravel 6 is deprecating Carbon v1:

> Carbon 1.x is no longer supported since it is nearing its maintenance end of life. Please upgrade your application to Carbon 2.0.

This package currently uses Carbon 1.2. Are there any plans to take this to Carbon 2.x?

**Comment by arctic-ice-cool** [comment]
Does this not work with Laravel 6?

**Comment by scottybo** [comment]
Not with the current dependency setup

**Comment by Fossil01** [comment]
This these need to be update to their latest versions:

```
"orchestra/testbench": "^4.0",
"phpunit/phpunit": "^8"
```

**Comment by driesvints** [comment]
I don't see any usages of Carbon in the package atm. Maybe it got removed by now?
