### ISSUE TITLE
Get EU VAT number details doesn´t work

### ISSUE THREAD

**Issue by Julen10** [mpociot/vat-calculator#90]
Hello,
I´m trying to replicate this example with real VAT number: https://github.com/mpociot/vat-calculator#get-eu-vat-number-details

But I get the following response:
```
object(stdClass)#1133 (6) {
  ["countryCode"]=>
  string(2) "ES"
  ["vatNumber"]=>
  string(9) "B75149773"
  ["requestDate"]=>
  string(16) "2020-01-22+01:00"
  ["valid"]=>
  bool(true)
  ["name"]=>
  string(3) "---"
  ["address"]=>
  string(3) "---"
}
```

The name and address is not defined as I can´t give them as input for the validation.

**Comment by xEsk** [comment]
I checked the SOAP response and it doesn't returns the name nor address, so the problem is not related with this library :(
