### ISSUE TITLE
Vat service check URL should be used over SSL

### ISSUE THREAD

**Issue by arun-s-yadav** [mpociot/vat-calculator#96]
Hi Team,

First of all, I would say thanks to the team for making this package and we started to use it in our development to calculate the VAT with laravel application.
![vat_service_url](https://user-images.githubusercontent.com/49061268/89522009-232c6b00-d7fe-11ea-9ffa-4b3869e88298.jpg)

Our team observed that to verify VAT number, you used URL set with this constant(VAT_SERVICE_URL) without SSL(https) which you should think to replace to use with SSL (with https).

We would suggest you add this improvement as earlier as possible.

Thanks,
Arun Yadav

**Comment by driesvints** [comment]
Will be in the next release, thanks.
